--1월27일
--SELECT문


DESC EMP;
DESC DEPT;
DESC BONUS;
DESC SALGRADE;

SELECT * FROM EMP;

SELECT 
    ENAME, JOB, HIREDATE 
FROM 
    EMP;

SELECT DEPTNO FROM EMP;

SELECT DISTINCT DEPTNO FROM EMP;

SELECT * FROM DEPT;

SELECT ENAME, SAL, SAL*12+COMM, COMM 
FROM EMP;

SELECT ENAME, SAL, [수입 출력하기], COMM
FROM EMP;

SELECT ENAME,
    SAL, SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+COMM AS ANN_SAL, 
    COMM 
FROM 
    EMP;

SELECT * FROM EMP ORDER BY SAL DESC;

SELECT *
    FROM EMP
ORDER BY DEPTNO ASC, SAL DESC;

--92P Q2
SELECT DISTINCT JOB
    FROM EMP;

--92P Q3
SELECT 
    EMPNO AS EMPLOYEE_NO, 
    ENAME AS EMPLOYEE_NAME,
    MGR AS MANAGER,
    SAL AS SALARY,
    COMM AS COMMISSION
    DEPTNO AS DEPARTMENT_NO
FROM EMP ORDER BY DEPTNO DESC, ENAME ASC;


SELECT *
    FROM EMP
    WHERE DEPTNO=30;
    
SELECT *
    FROM EMP
    WHERE DEPTNO=30
        AND JOB='SALESMAN';
        
SELECT *
    FROM EMP
    WHERE SAL*12=36000;
    
SELECT *
    FROM EMP
    WHERE SAL>=3000;
    
    
--10번 부서

SELECT *
    FROM EMP
    WHERE DEPTNO=10;

--10번 부서가 아닌

SELECT *
    FROM EMP
    WHERE DEPTNO!=10;

--SAL 1000 ~ 2000

SELECT *
    FROM EMP
    WHERE SAL>=1000
    AND SAL<=2000;

SELECT *
    FROM EMP
    WHERE SAL NOT BETWEEN 1000 AND 2000;

SELECT *
    FROM EMP
    WHERE JOB = 'MANAGER'
        OR JOB = 'SALESMAN'
        OR JOB = 'CLERK';

SELECT *
    FROM EMP
    WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');

SELECT *FROM
    FROM EMP
    WHERE JOB NOT IN ('MANAGER', 'SALESMAN', 'CLERK');
    
SELECT *
    FROM EMP
    WHERE ENAME LIKE 'S%';
    
SELECT *
    FROM EMP
    WHERE ENAME LIKE '_L%';
    
SELECT *
    FROM EMP
    WHERE ENAME LIKE '%AM%';
    
SELECT *
    FROM EMP
    WHERE ENAME NOT LIKE '%AM%';
    
SELECT *
    FROM EMP
    WHERE COMM IS NULL;
    
SELECT SAL, COMM, SAL + COMM FROM EMP;

SELECT *
    FROM EMP
    WHERE SAL > NULL
    AND DEPTNO = 30;
  
    
SELECT *
    FROM EMP
    WHERE COMM IS NULL
    AND DEPTNO = 30;
    
SELECT *
    FROM EMP
    WHERE SAL > NULL
    OR DEPTNO = 30;
    
SELECT *
    FROM EMP
    WHERE COMM IS NULL
    OR DEPTNO = 30;
     
 SELECT *
    FROM EMP
    WHERE SAL > NULL
    OR COMM IS NULL;
   

SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 10;
    
    
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 10;