--2월 1일 수요일


CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;
    
SELECT * FROM DEPT_TEMP;

--DROP TABLE DEPT_TEMP;

INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
                    VALUES (50, 'DATABASE', 'SEOUL');
                SELECT * FROM DEPT_TEMP;
 
INSERT INTO DEPT_TEMP
            VALUES(60, 'NETWORK', 'BUSAN');
                
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
            VALUES (70, 'WEB', NULL);
            
SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
            VALUES (80, 'MOBILE', '');
            
INSERT INTO DEPT_TEMP (DEPTNO, LOC)
            VALUES (90, 'BUSAN');
            
CREATE TABLE EMP_TEMP
        AS SELECT *
            FROM EMP
                WHERE 1 <> 1;

SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES (9999, '홍길동', 'PRESIDENT', NULL, '2001/01/01', 5000, 1000, 10);

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES (1111, '성춘향', 'MANAGER', 9999, '2001-01-05', 4000, NULL, 20);
                
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES (2111, '이순신', 'MANAGER', 9999, 
                                                                    TO_DATE('07/01/2001', 'DD/MM/YYYY'), 4000, NULL, 20);                

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES (3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);
            
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
        SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
            FROM EMP E, SALGRADE S
                WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                    AND S.GRADE = 1;
                    
CREATE TABLE DEPT_TEMP2 AS SELECT * FROM DEPT;

UPDATE DEPT_TEMP2
    SET LOC = 'SEOUL';
    
SELECT * FROM DEPT_TEMP2;

ROLLBACK;

UPDATE DEPT_TEMP2
    SET DNAME = 'DATABASE',
        LOC = 'SEOUL'
            WHERE DEPTNO = 40;

COMMIT;
            
UPDATE DEPT_TEMP2
    SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO =40)
    WHERE DEPTNO =40;
    
UPDATE DEPT_TEMP2
    SET LOC = 'SEOUL'
        WHERE DEPTNO = (SELECT DEPTNO FROM DEPT_TEMP2 WHERE DNAME = 'OPERATIONS');
        
SELECT * FROM DEPT_TEMP2;

SELECT *
    FROM DEPT_TEMP2 WHERE DEPTNO = 40;
    
CREATE TABLE EMP_TEMP2
    AS SELECT * FROM EMP;
    
DELETE FROM EMP_TEMP2
    WHERE JOB = 'MANAGER';
    
SELECT * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2
    WHERE EMPNO IN (SELECT E.EMPNO
                                          FROM EMP_TEMP2 E, SALGRADE S
                                          WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                                          AND S.GRADE = 3
                                          AND DEPTNO = 30);
                                          
DELETE FROM EMP_TEMP2;

CREATE TABLE DEPT_TCL
    AS SELECT *
        FROM DEPT;
 
        
SELECT * FROM DEPT_TCL;

INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');

UPDATE DEPT_TCL
    SET LOC = 'BUSAN'
        WHERE DEPTNO = 40;

DELETE DEPT_TCL WHERE DNAME = 'RESEARCH';

ROLLBACK;
COMMIT;

DELETE FROM DEPT_TCL
    WHERE DEPTNO = 50;
    
UPDATE DEPT_TCL SET LOC='SEOUL'
    WHERE DEPTNO = 30;
    
SELECT * FROM DEPT_TCL;

CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
    );
    
DESC EMP_DDL;

CREATE TABLE DEPT_DDL
    AS SELECT * FROM DEPT;
    
DESC DEPT_DDL;

SELECT * FROM DEPT_DDL;

CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;
    
ALTER TABLE EMP_ALTER
    ADD HP VARCHAR2(20);
    
SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
    RENAME COLUMN HP TO TEL;
    
ALTER TABLE EMP_ALTER
    MODIFY EMPNO NUMBER(5);
DESC EMP_ALTER;   

ALTER TABLE EMP_ALTER
    DROP COLUMN TEL;
    
RENAME EMP_ALTER TO EMP_RENAME;

SELECT * FROM EMP_RENAME;

TRUNCATE TABLE EMP_RENAME;

DROP TABLE EMP_RENAME;

CREATE TABLE DEPT_SEQUENCE
    AS SELECT *
        FROM DEPT
        WHERE 1 <> 1;
        
SELECT * FROM DEPT_SEQUENCE;

CREATE SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 10
    START WITH 10
    MAXVALUE 90
    MINVALUE 0
    NOCYCLE
    CACHE 2;
    
SELECT * FROM USER_SEQUENCES;

INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

SELECT SEQ_DEPT_SEQUENCE.CURRVAL
    FROM DUAL;
    
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 3
    MAXVALUE 99
    CYCLE;
    
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

CREATE TABLE TABLE_NOTNULL(
                        LOGIN_ID VARCHAR2(20) NOT NULL,
                        LOGIN_PWD VARCHAR2(20) NOT NULL,
                        TEL VARCHAR2(20)
                        );
                        
DESC TABLE_NOTNULL;

INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD, TEL)
                    VALUES ('TEST_ID_01', '1234', NULL);
                    
SELECT * FROM TABLE_NOTNULL;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
   FROM USER_CONSTRAINTS;
 
CREATE TABLE TABLE_NOTNULL2(
                        LOGIN_ID VARCHAR2(20) CONSTRAINT TBLNN2_LGNID_NN NOT NULL,
                        LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL,
                        TEL VARCHAR2(20)
                        );
                                                
ALTER TABLE TABLE_NOTNULL
MODIFY(TEL NOT NULL);

UPDATE TABLE_NOTNULL
    SET TEL = '010-1234-5678'
        WHERE LOGIN_ID = 'TEST_ID_01';
        
SELECT * FROM TABLE_NOTNULL;

ALTER TABLE TABLE_NOTNULL2
MODIFY(TEL CONSTRAINT TBLNN_TEL_NN NOT NULL);

DESC TABLE_NOTNULL2;

ALTER TABLE TABLE_NOTNULL2
RENAME CONSTRAINT TBLNN_TEL_NN TO TBLNN2_TEL_NN;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
   FROM USER_CONSTRAINTS;

ALTER TABLE TABLE_NOTNULL2
DROP CONSTRAINT TBLNN2_TEL_NN;

CREATE TABLE TABLE_UNIQUE(
                        LOGIN_ID VARCHAR2(20) UNIQUE,
                        LOGIN_PWD VARCHAR2(20) NOT NULL,
                        TEL VARCHAR2(20)
                        );
                        
DESC TABLE_UNIQUE;

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');
    
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES('TEST_ID_02', 'PWD01', '010-1234-5678');
    
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES(NULL, 'PWD01', '010-1234-5678');    

SELECT * FROM TABLE_UNIQUE;

UPDATE TABLE_UNIQUE
    SET LOGIN_ID='TEST_ID_01'
    WHERE LOGIN_ID IS NULL;
    
CREATE TABLE TABLE_UNIQUE2(
                        LOGIN_ID VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNID_UNQ UNIQUE,
                        LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNPW_NN NOT NULL,
                        TEL VARCHAR2(20)
                        );
                        
SELECT * FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';
    
ALTER TABLE TABLE_UNIQUE
MODIFY (TEL UNIQUE);

UPDATE TABLE_UNIQUE
    SET TEL = NULL;
    
SELECT * FROM TABLE_UNIQUE;

ALTER TABLE TABLE_UNIQUE2
MODIFY (TEL CONSTRAINT TBLUNQ_TEL_UNQ UNIQUE);

ALTER TABLE TABLE_UNIQUE2
RENAME CONSTRAINT TBLUNQ_TEL_UNQ TO TBLUNQ2_TEL_UNQ;

ALTER TABLE TABLE_UNIQUE2
DROP CONSTRAINT TBLUNQ2_TEL_UNQ;

CREATE TABLE TABLE_PK(
                        LOGIN_ID VARCHAR2(20) PRIMARY KEY,
                        LOGIN_PWD VARCHAR2(20) NOT NULL,
                        TEL VARCHAR2(20)
                        );
                        
DESC TABLE_PK;
    
CREATE TABLE TABLE_PK2(
                        LOGIN_ID VARCHAR2(20) CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY,
                        LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLPK2_LGNPW_NN NOT NULL,
                        TEL VARCHAR2(20)
                        );
INSERT INTO TABLE_PK(LOGIN_ID, lOGIN_PWD, TEL)
VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');

INSERT INTO TABLE_PK(LOGIN_ID, lOGIN_PWD, TEL)
VALUES('TEST_ID_01', 'PWD02', '010-2345-6789');

INSERT INTO TABLE_PK(LOGIN_ID, lOGIN_PWD, TEL)
VALUES(NULL, 'PWD02', '010-2345-6789');

INSERT INTO EMP
VALUES(9999, '홍길동', 'CLERK', '7788', SYSDATE, 1200, NULL, 50);

CREATE TABLE DEPT_FK(
                    DEPNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
                    DNAME VARCHAR2(14),
                    LOC VARCHAR2(13)
                    );
                    
CREATE TABLE EMP_FK(
                    EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
                    ENAME VARCHAR2(10),
                    JOB VARCHAR2(9),
                    MGR NUMBER(4),
                    HIREDATE DATE,
                    SAL NUMBER(7,2),
                    COMM NUMBER(7,2),
                    DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
                    );
                    
INSERT INTO EMP_FK
VALUES(9999, 'TEST_NAME', 'TEST_JOB', NULL, SYSDATE, 3000, NULL, 10);

INSERT INTO DEPT_FK
VALUES(10, 'TEST_DNAME', 'TEST_LOC');

DELETE FROM DEPT_FK
WHERE DEPTNO = 10;

CREATE TABLE TABLE_DEFAULT(
                    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK2_LOGINID_PK PRIMARY KEY,
                    LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
                    TEL VARCHAR2(20)
                    );
                    
INSERT INTO TABLE_DEFAULT VALUES ('TEST_ID', NULL, '010-1234-5678');

INSERT INTO TABLE_DEFAULT (LOGIN_ID, TEL) VALUES ('TEST_ID2', '010-1234-5678');

SELECT * FROM TABLE_DEFAULT;